[package]
name = "cspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { git = "https://github.com/CtrlZ233/rel4_comm.git", branch = "main" }
log = "0.4"